#ifndef VM_INSTRUCTIONS_H
#define VM_INSTRUCTIONS_H
#include <vm/ADC_imm.h>
#include <vm/ADC_X_ind.h>
#include <vm/ADC_abs.h>
#include <vm/ADC_abs_X.h>
#include <vm/ADC_abs_Y.h>
#include <vm/ADC_ind_Y.h>
#include <vm/ADC_zpg.h>
#include <vm/ADC_zpg_X.h>
#include <vm/AND_imm.h>
#include <vm/AND_X_ind.h>
#include <vm/AND_abs.h>
#include <vm/AND_abs_X.h>
#include <vm/AND_abs_Y.h>
#include <vm/AND_ind_Y.h>
#include <vm/AND_zpg.h>
#include <vm/AND_zpg_X.h>
#include <vm/ASL_A.h>
#include <vm/ASL_abs.h>
#include <vm/ASL_abs_X.h>
#include <vm/ASL_zpg.h>
#include <vm/ASL_zpg_X.h>
#include <vm/BCC_rel.h>
#include <vm/BCS_rel.h>
#include <vm/BEQ_rel.h>
#include <vm/BIT_abs.h>
#include <vm/BIT_zpg.h>
#include <vm/BMI_rel.h>
#include <vm/BNE_rel.h>
#include <vm/BPL_rel.h>
#include <vm/BRK_impl.h>
#include <vm/BVC_rel.h>
#include <vm/BVS_rel.h>
#include <vm/CLC_impl.h>
#include <vm/CLD_impl.h>
#include <vm/CLI_impl.h>
#include <vm/CLV_impl.h>
#include <vm/CMP_imm.h>
#include <vm/CMP_X_ind.h>
#include <vm/CMP_abs.h>
#include <vm/CMP_abs_X.h>
#include <vm/CMP_abs_Y.h>
#include <vm/CMP_ind_Y.h>
#include <vm/CMP_zpg.h>
#include <vm/CMP_zpg_X.h>
#include <vm/CPX_imm.h>
#include <vm/CPX_abs.h>
#include <vm/CPX_zpg.h>
#include <vm/CPY_imm.h>
#include <vm/CPY_abs.h>
#include <vm/CPY_zpg.h>
#include <vm/DEC_abs.h>
#include <vm/DEC_abs_X.h>
#include <vm/DEC_zpg.h>
#include <vm/DEC_zpg_X.h>
#include <vm/DEX_impl.h>
#include <vm/DEY_impl.h>
#include <vm/EOR_imm.h>
#include <vm/EOR_X_ind.h>
#include <vm/EOR_abs.h>
#include <vm/EOR_abs_X.h>
#include <vm/EOR_abs_Y.h>
#include <vm/EOR_ind_Y.h>
#include <vm/EOR_zpg.h>
#include <vm/EOR_zpg_X.h>
#include <vm/INC_abs.h>
#include <vm/INC_abs_X.h>
#include <vm/INC_zpg.h>
#include <vm/INC_zpg_X.h>
#include <vm/INX_impl.h>
#include <vm/INY_impl.h>
#include <vm/JMP_abs.h>
#include <vm/JMP_ind.h>
#include <vm/JSR_abs.h>
#include <vm/LDA_imm.h>
#include <vm/LDA_X_ind.h>
#include <vm/LDA_abs.h>
#include <vm/LDA_abs_X.h>
#include <vm/LDA_abs_Y.h>
#include <vm/LDA_ind_Y.h>
#include <vm/LDA_zpg.h>
#include <vm/LDA_zpg_X.h>
#include <vm/LDX_imm.h>
#include <vm/LDX_abs.h>
#include <vm/LDX_abs_Y.h>
#include <vm/LDX_zpg.h>
#include <vm/LDX_zpg_Y.h>
#include <vm/LDY_imm.h>
#include <vm/LDY_abs.h>
#include <vm/LDY_abs_X.h>
#include <vm/LDY_zpg.h>
#include <vm/LDY_zpg_X.h>
#include <vm/LSR_A.h>
#include <vm/LSR_abs.h>
#include <vm/LSR_abs_X.h>
#include <vm/LSR_zpg.h>
#include <vm/LSR_zpg_X.h>
#include <vm/NOP_impl.h>
#include <vm/ORA_imm.h>
#include <vm/ORA_X_ind.h>
#include <vm/ORA_abs.h>
#include <vm/ORA_abs_X.h>
#include <vm/ORA_abs_Y.h>
#include <vm/ORA_ind_Y.h>
#include <vm/ORA_zpg.h>
#include <vm/ORA_zpg_X.h>
#include <vm/PHA_impl.h>
#include <vm/PHP_impl.h>
#include <vm/PLA_impl.h>
#include <vm/PLP_impl.h>
#include <vm/ROL_A.h>
#include <vm/ROL_abs.h>
#include <vm/ROL_abs_X.h>
#include <vm/ROL_zpg.h>
#include <vm/ROL_zpg_X.h>
#include <vm/ROR_A.h>
#include <vm/ROR_abs.h>
#include <vm/ROR_abs_X.h>
#include <vm/ROR_zpg.h>
#include <vm/ROR_zpg_X.h>
#include <vm/RTI_impl.h>
#include <vm/RTS_impl.h>
#include <vm/SBC_imm.h>
#include <vm/SBC_X_ind.h>
#include <vm/SBC_abs.h>
#include <vm/SBC_abs_X.h>
#include <vm/SBC_abs_Y.h>
#include <vm/SBC_ind_Y.h>
#include <vm/SBC_zpg.h>
#include <vm/SBC_zpg_X.h>
#include <vm/SEC_impl.h>
#include <vm/SED_impl.h>
#include <vm/SEI_impl.h>
#include <vm/STA_X_ind.h>
#include <vm/STA_abs.h>
#include <vm/STA_abs_X.h>
#include <vm/STA_abs_Y.h>
#include <vm/STA_ind_Y.h>
#include <vm/STA_zpg.h>
#include <vm/STA_zpg_X.h>
#include <vm/STX_abs.h>
#include <vm/STX_zpg.h>
#include <vm/STX_zpg_Y.h>
#include <vm/STY_abs.h>
#include <vm/STY_zpg.h>
#include <vm/STY_zpg_X.h>
#include <vm/TAX_impl.h>
#include <vm/TAY_impl.h>
#include <vm/TSX_impl.h>
#include <vm/TXA_impl.h>
#include <vm/TXS_impl.h>
#include <vm/TYA_impl.h>
#endif//VM_INSTRUCTIONS_H
